name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.0
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm i

      - name: Build packages
        run: pnpm --filter "storybook-addon-remix-react-router" run build

      - name: Vitest cache
        uses: actions/cache@v4
        with:
          path: ./node_modules/.vite/vitest/results.json
          key: vitest-cache-${{ github.ref_name }}
          restore-keys: |
            vitest-cache-${{ github.ref_name }}

      - name: Run tests
        run: pnpm vitest --run

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm --filter "storybook-addon-remix-react-router" run release
